#!/usr/bin/env node

'use strict';

const CONFIG = 'ng-swagger-generate.json';
const fs = require('fs')

var options = null;

if (fs.existsSync(CONFIG)) {
  // It exists, read options from it
  options = JSON.parse(fs.readFileSync(CONFIG, "utf8"));
} else {
  // The config file doesn't exist. Log and exit.
  console.log("No file " + CONFIG + " in current directory. It means the " +
    "swagger file location is required. Usage: \n" + process.argv[1] +
    " <swagger.json> [output dir]");
  process.exit(1);
}

if (process.argv.indexOf('--stubs') !== -1) {
  options.stubs = true;
}

if (options.stubs === undefined) {
  options.stubs = false;
}

var ngSwaggerGen = require("./ng-swagger-generate.js");
for (var i in options.sources) {
  options.swagger = options.sources[i];
  ngSwaggerGen(options);
}
